<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pre-fortis clipping</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <!-- jQuery library -->

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function() {
          var audioElement = document.createElement('audio');
          audioElement.setAttribute('src', 'media/soundFiles/clipping/bee.mp3');
          audioElement.load()

          $.get();

          audioElement.addEventListener("load", function() {
              audioElement.play();
          }, true);

          $('.play').click(function() {
              audioElement.play();
          });

      });
  </script>
</head>

<body>
  <h1 class="text-center">Pre-fortis clipping</h1>


  <div class="container">
    <table class="table  table-hover table-responsive table-bordered">

     <thead class="thead-default">
     <tr>
      <th></th>
      <th></th>
      <th>d</th>
      <th>t</th>
      <th>g</th>
      <th>k</th>
      <th>v</th>
      <th>f</th>
      <th>z</th>
      <th>s</th>
     </tr>
   </thead>

     <tr>
      <th rowspan="12">i&#720;</th>
      <td>bee <span class="glyphicon glyphicon-play-circle play"></span></td>
      <td>bead</td>
      <td>beat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>fee</td>
      <td>feed</td>
      <td>feet</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>he</td>
      <td>heed</td>
      <td>heat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>knee</td>
      <td>need</td>
      <td>neat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>knees</td>
      <td>niece</td>
     </tr>
     <tr>
      <td>lea</td>
      <td></td>
      <td></td>
      <td>league</td>
      <td>leak</td>
      <td>leave</td>
      <td>leaf</td>
      <td>leas</td>
      <td>lease</td>
     </tr>
     <tr>
      <td>me</td>
      <td>mead</td>
      <td>meat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>pea</td>
      <td>peed</td>
      <td>peat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>peas</td>
      <td>peace</td>
     </tr>
     <tr>
      <td>plea</td>
      <td>plead</td>
      <td>pleat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>see</td>
      <td>seed</td>
      <td>seat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>seize</td>
      <td>cease</td>
     </tr>
     <tr>
      <td>she</td>
      <td>she'd</td>
      <td>sheet</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>tea</td>
      <td>teed</td>
      <td>teat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>we</td>
      <td>weed</td>
      <td>wheat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th rowspan="4">&#593;&#720;</th>
      <td>bar</td>
      <td>bard</td>
      <td>Bart</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>car</td>
      <td>card</td>
      <td>cart</td>
      <td></td>
      <td></td>
      <td>calve</td>
      <td>calf</td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>halve</td>
      <td>half</td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>spa</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>spas</td>
      <td>sparce</td>
     </tr>

     <tr>
      <th rowspan="2">&#604;&#720;</th>
      <td>her</td>
      <td>heard</td>
      <td>hurt</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>hers</td>
      <td>hearse</td>
     </tr>

     <tr>
      <td>were</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>whirrs</td>
      <td>worse</td>
     </tr>

     <tr>
      <th rowspan="5">u&#720;</th>
      <td>shoe</td>
      <td>shoed</td>
      <td>shoot</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>Jew</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Jews</td>
      <td>juice</td>
     </tr>
     <tr>
      <td>moo</td>
      <td>mood</td>
      <td>moot</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>moos</td>
      <td>moose</td>
     </tr>
     <tr>
      <td>loo</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>lose</td>
      <td>loose</td>
     </tr>
     <tr>
      <td>who</td>
      <td>who'd</td>
      <td>hoot</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th rowspan="5">&#596;&#720;</th>
      <td>core</td>
      <td>cord</td>
      <td>court</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>cause</td>
      <td>course</td>
     </tr>
     <tr>
      <td>more</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>moors</td>
      <td>Morse</td>
     </tr>
     <tr>
      <td>or</td>
      <td>awed</td>
      <td>ought</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>saw</td>
      <td>sawed</td>
      <td>sought</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>saws</td>
      <td>source</td>
     </tr>
     <tr>
      <td>whore</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>whores</td>
      <td>horse</td>
     </tr>

     <tr>
      <th rowspan="6">e&#618;</th>
      <td>gray</td>
      <td>grade</td>
      <td>great</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>greys</td>
      <td>grace</td>
     </tr>
     <tr>
      <td>lay</td>
      <td>laid</td>
      <td>late</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>lays</td>
      <td>lace</td>
     </tr>
     <tr>
      <td>may</td>
      <td>made</td>
      <td>mate</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>maze</td>
      <td>mace</td>
     </tr>
     <tr>
      <td>play</td>
      <td>played</td>
      <td>plate</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>plays</td>
      <td>place</td>
     </tr>
     <tr>
      <td>stay</td>
      <td>stayed</td>
      <td>state</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>way</td>
      <td>weighed</td>
      <td>wait</td>
      <td></td>
      <td></td>
      <td>wave</td>
      <td>waif</td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th rowspan="13">a&#618;</th>
      <td>die</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>dies</td>
      <td>dice</td>
     </tr>
     <tr>
      <td>eye</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>eyes</td>
      <td>ice</td>
     </tr>
     <tr>
      <td>fry</td>
      <td>fried</td>
      <td>fright</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>high</td>
      <td>hide</td>
      <td>height</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>lie</td>
      <td>lied</td>
      <td>light</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>lies</td>
      <td>lice</td>
     </tr>
     <tr>
      <td>pry</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>prize</td>
      <td>price</td>
     </tr>
     <tr>
      <td>rye</td>
      <td>ride</td>
      <td>write</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>rise</td>
      <td>rice</td>
     </tr>
     <tr>
      <td>sigh</td>
      <td>side</td>
      <td>site</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>spy</td>
      <td>spied</td>
      <td>spite</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>spies</td>
      <td>spice</td>
     </tr>
     <tr>
      <td>tie</td>
      <td>tide</td>
      <td>tight</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>try</td>
      <td>tried</td>
      <td>trite</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>vie</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>vies</td>
      <td>vice</td>
     </tr>
     <tr>
      <td>why</td>
      <td>wide</td>
      <td>white</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th rowspan="2">&#596;&#618;</th>
      <td>boy</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>boys</td>
      <td>Boyce</td>
     </tr>
     <tr>
      <td>joy</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>joys</td>
      <td>Joyce</td>
     </tr>

     <tr>
      <th rowspan="8">&#601;&#650;</th>
      <td>bow</td>
      <td>bode</td>
      <td>boat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>doe</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>doze</td>
      <td>dose</td>
     </tr>
     <tr>
      <td>flow</td>
      <td>flowed</td>
      <td>float</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>go</td>
      <td>goad</td>
      <td>goat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>mow</td>
      <td>mode</td>
      <td>moat</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>no</td>
      <td>node</td>
      <td>note</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>row</td>
      <td>rode</td>
      <td>wrote</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>tow</td>
      <td>towed</td>
      <td>tote</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th>a&#650;</th>
      <td>bough</td>
      <td>bowed</td>
      <td>bout</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>

     <tr>
      <th>e&#601;</th>
      <td>scare</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>scares</td>
      <td>scarce</td>
     </tr>

     <tr>
      <th>&#618;&#601;</th>
      <td>fear</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>fears</td>
      <td>fierce</td>
     </tr>
     <!-- <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>A</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>As</td>
      <td>ace</td>
     </tr>
     <tr>
      <td>allow</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>allows</td>
      <td>a louse</td>
     </tr>
     <tr>
      <td>bray</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>brays</td>
      <td>brace</td>
     </tr>
     <tr>
      <td>cur</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>curs</td>
      <td>curse</td>
     </tr>
     <tr>
      <td>dhow</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>dhow</td>
      <td>douse</td>
     </tr>
     <tr>
      <td>grow</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>grows</td>
      <td>gross</td>
     </tr>
     <tr>
      <td>hoe</td>
      <td>hosed</td>
      <td>host</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
     </tr>
     <tr>
      <td>how</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>how's</td>
      <td>house</td>
     </tr>
     <tr>
      <td>K</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Ks</td>
      <td>case</td>
     </tr>
     <tr>
      <td>pay</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>pays</td>
      <td>pace</td>
     </tr>
     <tr>
      <td>peer</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>peers</td>
      <td>pierce</td>
     </tr>
     <tr>
      <td>purr</td>
      <td>purred</td>
      <td>pert</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>purrs</td>
      <td>purse</td>
     </tr>
     <tr>
      <td>spay</td>
      <td>spayed</td>
      <td>spate</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>spays</td>
      <td>space</td>
     </tr>
     <tr>
      <td>tray</td>
      <td>trade</td>
      <td>trait</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>trays</td>
      <td>trace</td>
     </tr>
     <tr>
      <td>ray</td>
      <td>raid</td>
      <td>rate</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>rays</td>
      <td>race</td>
     </tr> -->
    </table>

  </div>
</body>
</html>
